### ISSUE TITLE
Building fails when processing Markdown source files

### ISSUE THREAD

**Issue by mchubby** [fanf2/regpg#3]
#### Steps to reproduce ####

Platform is Debian 8, with packages make and libtext-markdown-perl.

```bash
~/regpg-regpg-0.99$ LANG=C make
```

#### Expected ####

No errors; files generated in doc/

#### Observed ####

Errors out as follow:
```
util/markdown.pl doc/contributing.md doc/contributing.html
Undefined subroutine &Text::Markdown::Markdown called at util/markdown.pl line 29, <$hin> chunk 1.
Makefile:75: recipe for target 'doc/contributing.html' failed
make: *** [doc/contributing.html] Error 255
```

**Comment by fanf2** [comment]
Oh, good catch, thanks!

I'm using the `markdown` package (John Gruber's original version), whereas you have `libtext-markdown-perl`. Unfortunately they conflict with each other because they both stamp on the Text::Markdown namespace.

I will shortly push a revision to `regpg`'s README that makes this more clear.
